### ISSUE TITLE
IndexError while using graph_transitions

### ISSUE THREAD

**Issue by orf** [kmmbvnr/django-fsm#106]
**Edit:** I needed to include the choices kwarg to `FSMIntegerField`. Perhaps it would be a good idea to print an error message when this happens rather than failing with an exception?

_Original:_

Hello,
I have this model that simulates a QA process using django-fsm:

```
class QAState(enum.IntEnum):
    NEW = 1
    TECH_QA = 2
    COMPLETED = 5


class QAMixin(ConcurrentTransitionMixin, models.Model):
    qa_state = FSMIntegerField(default=QAState.NEW, protected=True)

    @transition(qa_state, source=QAState.NEW, target=QAState.TECH_QA)
    def send_for_tech_qa(self, user: User):
        pass

    @transition(qa_state, source=QAState.TECH_QA, target=QAState.NEW)
    def failed_tech_qa(self, user: User):
        pass

    @transition(qa_state, source=QAState.TECH_QA, target=QAState.COMPLETED)
    def passed_tech_qa(self, user: User):
        pass

    class Model:
        abstract = True
```

Whenever I try to run `graph_transitions` the following error occurs:

```
Traceback (most recent call last):
  File "/home/vagrant/.pycharm_helpers/pycharm/django_manage.py", line 41, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/usr/lib/python3.4/runpy.py", line 182, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/doge/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/venv/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django_fsm/management/commands/graph_transitions.py", line 161, in handle
    dotdata = generate_dot(fields_data)
  File "/home/vagrant/venv/lib/python3.4/site-packages/django_fsm/management/commands/graph_transitions.py", line 49, in generate_dot
    source_label = [smart_text(name[1]) for name in field.choices if name[0] == transition.source][0]
IndexError: list index out of range
```

This doesn't happen if there are no transitions on the model, but as far as I can tell the QAMixin is working? I've tested the transitions themselves and that all works?

**Comment by kmmbvnr** [comment]
Yeah, I'm actually not using the graph_transition code for a while, and after several Github contributions, it's became a crap.

So, I'm closing this feature, since I'm not going to fix it in a meaningful time, but pull requests are welcome anyway.
