### ISSUE TITLE
graph_transitions blows up sometimes

### ISSUE THREAD

**Issue by lwm** [kmmbvnr/django-fsm#121]
This code:
```
for mtuple in apps.get_app_config(app).models.items():
    mname, mclass = mtuple[0], mtuple[1]
    fname = join(transitions_dir, '{}.{}'.format(mname.lower(), ftype))
    if hasattr(mclass, 'transitions'):
        call_command(
                'graph_transitions',
                '{}.{}'.format(app, mname),
                outputfile=fname,
                layout=layout
            )
```

works sometimes, and other times:

```
lwm$ envd ./manage.py generate_transitions
INFO:root:settings.ENVIRONMENT: dev
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/lwm/work/lock8/velodrome/velodrome/lock8/management/commands/generate_transitions.py", line 30, in handle
    layout=layout
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django_fsm/management/commands/graph_transitions.py", line 161, in handle
    dotdata = generate_dot(fields_data)
  File "/home/lwm/work/lock8/velodrome/.venv/lib/python3.5/site-packages/django_fsm/management/commands/graph_transitions.py", line 62, in generate_dot
    edges.add((source_name, on_error_name, (('style', 'dotted'),)))
UnboundLocalError: local variable 'source_name' referenced before assignment
```

**Comment by kmmbvnr** [comment]
Can you create a reproducible use-case?
