### ISSUE TITLE
graph_transitions: AttributeError on Django 1.10

### ISSUE THREAD

**Issue by akhayyat** [kmmbvnr/django-fsm#146]
The `graph_transitions` command fails on Django 1.10 with the following traceback:

``` pytb
$ ./manage.py graph_transitions
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "<venv>/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "<venv>/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "<venv>/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "<venv>/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "<venv>/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<venv>/lib/python3.5/site-packages/django_fsm/management/commands/graph_transitions.py", line 102, in <module>
    class Command(BaseCommand):
  File "<venv>/lib/python3.5/site-packages/django_fsm/management/commands/graph_transitions.py", line 105, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

Switching to Django 1.9.2 gets rid of this error. Would appreciate fixing the command on Django 1.10.

**Comment by kmmbvnr** [comment]
Pull request are welcome

**Comment by dirkmoors** [comment]
Any update on this?
