### ISSUE TITLE
graph_transitions - TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ferenc-radius** [kmmbvnr/django-fsm#169]
When i execute the command inside a docker container (python:3.6-slim)

python manage.py graph_transitions -o output.jpg

> Traceback (most recent call last):
>   File "manage.py", line 9, in <module>
>     execute_from_command_line(sys.argv)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
>     utility.execute()
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.6/site-packages/django_fsm/management/commands/graph_transitions.py", line 189, in handle
>     dotdata = generate_dot(fields_data)
>   File "/usr/local/lib/python3.6/site-packages/django_fsm/management/commands/graph_transitions.py", line 85, in generate_dot
>     subgraph.node(name, label=label, shape='doublecircle')
>   File "/usr/local/lib/python3.6/site-packages/graphviz/dot.py", line 104, in node
>     attributes = self.attributes(label, attrs, _attributes)
>   File "/usr/local/lib/python3.6/site-packages/graphviz/lang.py", line 91, in attributes
>     result = ['label=%s' % quote(label)]
>   File "/usr/local/lib/python3.6/site-packages/graphviz/lang.py", line 44, in quote
>     if html(identifier):
> TypeError: expected string or bytes-like object

**Comment by kmmbvnr** [comment]
Is it Python 3.6 problem? Have you tried python 3.5?

**Comment by shaumux** [comment]
I'm getting a similar error on python 2.7
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django_fsm/management/commands/graph_transitions.py", line 189, in handle
    dotdata = generate_dot(fields_data)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/django_fsm/management/commands/graph_transitions.py", line 85, in generate_dot
    subgraph.node(name, label=label, shape='doublecircle')
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/graphviz/dot.py", line 104, in node
    attributes = self.attributes(label, attrs, _attributes)
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/graphviz/lang.py", line 91, in attributes
    result = ['label=%s' % quote(label)]
  File "/home/shaumux/.virtualenvs/iris/lib/python2.7/site-packages/graphviz/lang.py", line 44, in quote
    if html(identifier):
TypeError: expected string or buffer
```

**Comment by JamesPeabody** [comment]
I believe line 85 of graph_transitions.py should read:
`subgraph.node(name, label=label.name)`
rather than 
`subgraph.node(name, label=label)`

label is of type enum rather than the str value of the enum.

After making this change, I was presented with a lovely picture. We all know how attached management gets to lovely pictures.

Thanks for the efforts!

**Comment by akhoronko** [comment]
I've got the same error when using django's lazy translations for FSMField choices labels

**Comment by florianm** [comment]
With django-fsm 2.6.0, I've had to wrap a `str()` around the `label=str(label)` statement in lines 85 but not 87. Leaving this comment here as a quick and dirty hack.

**Comment by SaadBazaz** [comment]
Getting this same issue, does this happen because I've attached choices to the FSMField and the key of each choice is an integer?
