### ISSUE TITLE
Incompatibility with django 1.11.10

### ISSUE THREAD

**Issue by mullerivan** [kmmbvnr/django-fsm#202]
Hi there
django-fsm==2.4.0
django-fsm-admin==1.2.3
django-fsm-log==1.3.0
Django==1.11.10

Voodoo  hack to have a  profile mixing that  is not  working anymore...

`    def __getattribute__(self, item):
        value = super(ProfileMixin, self).__getattribute__(item)
        if item in SHARED_FIELDS:
            if self.profile:
                return super(ClientProfile, self.profile).__getattribute__(item)
        return value
`

 File "MY_FILE", line 75, in __getattribute__
    value = super(ProfileMixin, self).__getattribute__(item)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 226, in __get__
    return self.field.get_state(instance)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 266, in get_state
    return instance.__dict__[self.name]
KeyError: 'state'`

`

**Comment by kmmbvnr** [comment]
The provided code sample is not from django-fsm

**Comment by mullerivan** [comment]
Hi there i already update  with django-fsm==2.6.0
and coment  my code  but the  problem still there

Internal Server Error: /signup/clients/282/get_edit_form
Traceback (most recent call last):
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ivan/encode/amlnz/aml_nz/signup/views/clients.py", line 207, in post
    **kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/views/generic/base.py", line 155, in get
    context = self.get_context_data(**kwargs)
  File "/home/ivan/encode/amlnz/aml_nz/signup/views/clients.py", line 201, in get_context_data
    {'form': self.get_form_class()(**self.get_form_kwargs())})
  File "/home/ivan/encode/amlnz/aml_nz/aml_validations/forms/subclients/base_subclient_form.py", line 35, in __init__
    super(BaseSubClientForm, self).__init__(*args, **kwargs)
  File "/home/ivan/encode/amlnz/aml_nz/core/forms/has_form_helper.py", line 18, in __init__
    super(HasFormHelperMixin, self).__init__(*args, **kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/forms/models.py", line 302, in __init__
    object_data = model_to_dict(instance, opts.fields, opts.exclude)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/forms/models.py", line 97, in model_to_dict
    data[f.name] = f.value_from_object(instance)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 897, in value_from_object
    return getattr(obj, self.attname)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/query.py", line 63, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/base.py", line 583, in from_db
    new = cls(*values)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/polymorphic/models.py", line 151, in __init__
    super(PolymorphicModel, self).__init__(*args, ** kwargs)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/base.py", line 574, in __init__
    super(Model, self).__init__()
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 444, in __init__
    self._update_initial_state()
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 485, in _update_initial_state
    (field.attname, field.value_from_object(self)) for field in self.state_fields
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 485, in <genexpr>
    (field.attname, field.value_from_object(self)) for field in self.state_fields
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 897, in value_from_object
    return getattr(obj, self.attname)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 226, in __get__
    return self.field.get_state(instance)
  File "/home/ivan/encode/amlnz/local/lib/python2.7/site-packages/django_fsm/__init__.py", line 266, in get_state
    return instance.__dict__[self.name]
KeyError: 'state'
"POST /signup/clients/282/get_edit_form HTTP/1.1" 500 27762
"POST /signup/clients/282/get_edit_form HTTP/1.1" 500 27762
