### ISSUE TITLE
Error on graph_transitions

### ISSUE THREAD

**Issue by lucacorti** [kmmbvnr/django-fsm#77]
I'm getting this when running the `graph_transitions` management command.

```
venv/lib/python2.7/site-packages/django_fsm_log/models.py:5: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import GenericForeignKey

venv/lib/python2.7/site-packages/django_fsm_log/apps.py:14: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  backend = import_by_path(settings.DJANGO_FSM_LOG_STORAGE_METHOD)

venv/lib/python2.7/site-packages/django/core/management/base.py:259: RemovedInDjango19Warning: "requires_model_validation" is deprecated in favor of "requires_system_checks".
  RemovedInDjango19Warning)

venv/lib/python2.7/site-packages/django_fsm/management/commands/graph_transitions.py:102: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
  model = get_model(field_spec[0], field_spec[1])

venv/python2.7/site-packages/django/db/models/__init__.py:55: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from . import loading

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "venv/lib/python2.7/site-packages/django_fsm/management/commands/graph_transitions.py", line 112, in handle
    dotdata = generate_dot(fields_data)
  File "venv/lib/python2.7/site-packages/django_fsm/management/commands/graph_transitions.py", line 55, in generate_dot
    subgraph.node(name, label=label, shape='doublecircle')
  File "venv/lib/python2.7/site-packages/graphviz/dot.py", line 99, in node
    attributes = self.attributes(label, attrs, _attributes)
  File "venv/lib/python2.7/site-packages/graphviz/lang.py", line 91, in attributes
    result = ['label=%s' % quote(label)]
  File "venv/lib/python2.7/site-packages/graphviz/lang.py", line 44, in quote
    if html(identifier):
TypeError: expected string or buffer
```

**Comment by kmmbvnr** [comment]
pull request welcome =)

**Comment by mrtarunjain** [comment]
Hi ,  I am getting a similar error.
`TypeError: expected string or bytes-like object` when running `graph_transitions`.
Can someone tell me why this is happening? And what is the fix/workaround?
