### ISSUE TITLE
AttributeError while running through document coverage with Sphinx

### ISSUE THREAD

**Issue by gergelypolonkai** [kmmbvnr/django-fsm#92]
When I use Sphinx doc coverage build, I get the following error:

    Traceback (most recent call last):
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/cmdline.py", line 245, in main
        app.build(opts.force_all, filenames)
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/application.py", line 264, in build
        self.builder.build_update()
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 240, in build_update
        self.build(['__all__'], to_build)
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 316, in build
        self.write(docnames, list(updated_docnames), method)
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/ext/coverage.py", line 77, in write
        self.build_py_coverage()
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/sphinx/ext/coverage.py", line 190, in build_py_coverage
        attr = getattr(obj, attr_name)
      File "/home/polesz/dem/venv/lib/python2.7/site-packages/django_fsm/__init__.py", line 205, in __get__
        raise AttributeError('Can only be accessed via an instance.')
    AttributeError: Can only be accessed via an instance.

After some debugging it turned out that `coverage.py` gets the attributes of my model class, not an actual object. Adding an

    import types

at the beginning of `__init__.py`, and a changing the beginning of `__get__()` like this (note that I changed the `type` parameter to `obj_type` as `type` is a reserved word):

    def __get__(self, instance, obj_type=None):
        if isinstance(obj_type, (type, types.ClassType)):
            return
    …

fixes the problem (although seems to be a bit ugly).

**Comment by kmmbvnr** [comment]
This actually resembles behavior of `FileField` from django - https://github.com/django/django/blob/master/django/db/models/fields/files.py#L174

You should have the ame problems with File and Image build-in django fields.

Sorry, but I think "fixing" django-fsm is not a solution.

It's the problem of Sphinx doc coverage.

**Comment by gergelypolonkai** [comment]
Never met that bug before. Of course, if this is not an actual bug, you
shouldn't fix it. Thanks for the pointer, I'll take it to Sphinx, then.
